apiVersion: v2
appVersion: latest
dependencies:
    -   name: liferay-default
        repository: file://../default
        version: 0.1.4
description:
    Liferay is an all-in-one DXP, LCAP, and Commerce platform. This chart is optimized for AWS.
icon: https://www-cdn.liferay.com/documents/d/guest/liferay-logo
name: liferay-gcp
type: application
version: 0.1.5