{{- if .Values.enabled -}}
---
# 1. SecretStore for Liferay License (GCP Secret Manager)
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: liferay-license-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ $.Values.gcp.projectId | quote }}
---
# 2. ExternalSecret for Liferay License
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: liferay-license
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: liferay-license-store
  target:
    name: liferay-license
    creationPolicy: Owner
    template:
      data:
        license.xml: "{{ `{{ .license }}` }}"
  data:
  - secretKey: license
    remoteRef:
      key: liferay-cloud-native-liferay-license-xml
{{- end -}}
