apiVersion: v2
appVersion: latest
description:
    Liferay is an all-in-one DXP, LCAP, and Commerce platform. This chart creates cloud infrastructure resources to support Liferay.
icon: https://www-cdn.liferay.com/documents/d/guest/liferay-logo
name: liferay-gcp-infrastructure
type: application
version: 0.1.3