apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-80"
    name: provider-gcp-sql
spec:
    package: xpkg.upbound.io/upbound/provider-gcp-sql:v2.4.0
    runtimeConfigRef:
        name: gcp-sql-config
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-80"
    name: provider-gcp-storage
spec:
    package: xpkg.upbound.io/upbound/provider-gcp-storage:v2.4.0
    runtimeConfigRef:
        name: gcp-storage-config
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-80"
    name: provider-gcp-compute
spec:
    package: xpkg.upbound.io/upbound/provider-gcp-compute:v2.4.0
    runtimeConfigRef:
        name: gcp-compute-config
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
    annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true
        argocd.argoproj.io/sync-wave: "-80"
    name: provider-kubernetes
spec:
    package: xpkg.upbound.io/upbound/provider-kubernetes:v1.2.0
    runtimeConfigRef:
        name: kubernetes-config
    skipDependencyResolution: true
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-80"
    name: provider-gcp-cloudplatform
spec:
    package: xpkg.upbound.io/upbound/provider-gcp-cloudplatform:v2.4.0
    runtimeConfigRef:
        name: gcp-cloudplatform-config