{{- if .Values.ingress.tls }}
{{- range $tls := .Values.ingress.tls }}
apiVersion: v1
data:
    tls.crt: {{ $tls.cert | b64enc }}
    tls.key: {{ $tls.key | b64enc }}
kind: Secret
metadata:
    name: {{ $tls.secretName }}
    namespace: {{ include "liferay.namespace" $ }}
type: kubernetes.io/tls
---
{{- end }}
{{- end }}