{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    {{- with .Values.serviceAccount.role.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    labels:
        {{- include "liferay.labels" . | nindent 8 }}
    name: {{ include "liferay.name" . }}
    namespace: {{ include "liferay.namespace" . }}
{{- with .Values.serviceAccount.role.rules }}
rules:
    {{- toYaml . | nindent 4 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels:
        {{- include "liferay.labels" . | nindent 8 }}
    name: {{ include "liferay.name" . }}
    namespace: {{ include "liferay.namespace" . }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ include "liferay.name" . }}
subjects:
    -   kind: ServiceAccount
        name: {{ include "liferay.serviceAccountName" . }}
        namespace: {{ include "liferay.namespace" . }}
---
apiVersion: v1
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
kind: ServiceAccount
metadata:
    {{- with .Values.serviceAccount.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    labels:
        {{- include "liferay.labels" . | nindent 8 }}
    name: {{ include "liferay.serviceAccountName" . }}
    namespace: {{ include "liferay.namespace" . }}
{{- end }}