apiVersion: v1
kind: ConfigMap
metadata:
  name: liferay-company-domain-config
  namespace: {{ .Release.Namespace }}
data:
  LIFERAY_COMPANY_PERIOD_DEFAULT_PERIOD_VIRTUAL_PERIOD_HOST_PERIOD_NAME: {{ printf "%s.%s" .Release.Namespace .Values.rootDomain | quote }}
  LIFERAY_COMPANY_PERIOD_DEFAULT_PERIOD_WEB_PERIOD_ID: {{ printf "%s.%s" .Release.Namespace .Values.rootDomain | quote }}