gcp:
  projectId: ""
  clusterName: ""
  githubWorkloadIdentityPoolId: ""
  sqlGoogleServiceAccountEmail: ""
  storageGoogleServiceAccountEmail: ""
  computeGoogleServiceAccountEmail: ""
  cloudplatformGoogleServiceAccountEmail: ""
crossplaneNamespace: crossplane-system